### ISSUE TITLE
uvface attribute error in mesh.py

### ISSUE THREAD

**Issue by QianqianF** [ubcspin/foldmold#63]
Catch this error when exporting the standard box. Possibly related to model size or edge changing code.
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/foldmold/io_export_paper_model.py", line 596, in invoke
    self.prepare(context)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/foldmold/io_export_paper_model.py", line 584, in prepare
    limit_by_page=sce.paper_model.limit_by_page)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/foldmold/io_export_paper_model.py", line 105, in prepare
    self.mesh.generate_cuts(cage_size / scale if limit_by_page and cage_size else None, priority_effect)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/foldmold/mesh.py", line 101, in generate_cuts
    old_island = join(edge_a, edge_b, size_limit=page_size)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/foldmold/mesh.py", line 653, in join
    is_right_ccw = right.is_uvface_upwards() ^ (right.max.tup == position)
AttributeError: max
```
We should improve this error message to include how to add a seam.
![image](https://user-images.githubusercontent.com/32441593/85345519-8741dc80-b4a7-11ea-972b-72c4d65730ea.png)

Current workaround: apply seams to all edges

**Comment by QianqianF** [comment]
fixed by ed7b3a1abf74
